export const appOptions = [
    { label: "New Order", value: "New Order" },
    { label: "Draft Order", value: "Draft Order" },
    { label: "Submitted Order", value: "Submitted Order" },
  ];
  
  export const supplierOptions = [
    { label: "ABC", value: "abc" },
    { label: "Beacon", value: "beacon" },
    { label: "SRS", value: "srs" },
  ];
  
  export const templateOptions = [
    { label: "Template 1 (Blank)", value: "template1", items: [] },
    { label: "Template 2 (Test Template)", value: "template2", 
      items: [
          {
            sku: "02OC025AEG - A",
            title: "Owens Corning Oakridge AR - Estate Grey",
            qty: 10,
            uom: "SQ",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["SQ", "BNDL"],
          },
          {
            sku: "ST-OC-EST - A",
            title: "Owens Corning Starter Strip",
            qty: 10,
            uom: "EA",
            variant: "-",
            unitPrice: 18.25,
            basePrice: 18.25,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "RC-OC-EST - A",
            title: "Owens Corning Ridge Cap",
            qty: 10,
            uom: "EA",
            variant: "-",
            unitPrice: 9.75,
            basePrice: 9.75,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "UL-GFT-100 - A",
            title: "Synthetic Underlayment – 10-SQ roll",
            qty: 5,
            uom: "RL",
            variant: "-",
            unitPrice: 20.0,
            basePrice: 20.0,
            linePrice: 0.0,
            uoms: ["RL"],
          },
          {
            sku: "IW-36-75 - A",
            title: 'Ice & Water Shield 36" × 75′',
            qty: 3,
            uom: "RL",
            variant: "-",
            unitPrice: 23.5,
            basePrice: 23.5,
            linePrice: 0.0,
            uoms: ["RL"],
          },
        ],
     },
     { label: "*Template 3 (ABC Template)", value: "template3", 
      items: [
          {
            sku: "02OCO25AEG",
            title: "Owens Corning Oakridge Algae Resistant Estate Gray 3 Bundle Per Square",
            qty: 1,
            uom: "SQ",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["SQ", "BNDL"],
          },
          {
            sku: "04OCPEEG",
            title: "Owens Corning Proedge Estate Gray 33 Linear Feet Per Bundle",
            qty: 1,
            uom: "BNDL",
            variant: "-",
            unitPrice: 18.25,
            basePrice: 18.25,
            linePrice: 0.0,
            uoms: ["BNDL"],
          },
          {
            sku: "04OCSSPL",
            title: "Owens Corning Starter Strip Plus 105 Linear Feet per Bundle",
            qty: 1,
            uom: "BNDL",
            variant: "-",
            unitPrice: 9.75,
            basePrice: 9.75,
            linePrice: 0.0,
            uoms: ["BNDL"],
          },
          {
            sku: "11IWRREE20",
            title: "Owens Corning RhinoRoof U20 Everything Exterior Roofing 10 Square Roll",
            qty: 5,
            uom: "RL",
            variant: "-",
            unitPrice: 20.0,
            basePrice: 20.0,
            linePrice: 0.0,
            uoms: ["RL"],
          },
          {
            sku: "11OCWLM2",
            title: "Owens Corning Weatherlock Mat 3' X 66.7' 2 Square Per Roll",
            qty: 3,
            uom: "RL",
            variant: "-",
            unitPrice: 23.5,
            basePrice: 23.5,
            linePrice: 0.0,
            uoms: ["RL"],
          },
          {
            sku: "17OCVS4N",
            title: `Owens Corning Ventsure 12" X 4' Strip With Nails`,
            qty: 3,
            uom: "EA",
            variant: "-",
            unitPrice: 23.5,
            basePrice: 23.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "2006677915",
            title: "Rust-Oleum Oil Based Protective Enamel White Satin 1 Qt",
            qty: 3,
            uom: "EA",
            variant: "-",
            unitPrice: 23.5,
            basePrice: 23.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "16MHCB2115",
            title: "Mule-Hide CO-Brand 211 Plastic Cement 5 Gallons",
            qty: 3,
            uom: "EA",
            variant: "-",
            unitPrice: 23.5,
            basePrice: 23.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "15MIPC1142",
            title: `Plastic Cap Nails 1-1/4" 2,000 Per Box`,
            qty: 3,
            uom: "BX",
            variant: "-",
            unitPrice: 23.5,
            basePrice: 23.5,
            linePrice: 0.0,
            uoms: ["BX"],
          },
          {
            sku: "15MIPC1142",
            title: `Plastic Cap Nails 1-1/4" 2,000 Per Box`,
            qty: 3,
            uom: "BX",
            variant: "-",
            unitPrice: 23.5,
            basePrice: 23.5,
            linePrice: 0.0,
            uoms: ["BX"],
          },
          {
            sku: "14IP81710",
            title: `Ips 1-3 Mill Galvanized Base Pipe Flashing`,
            qty: 3,
            uom: "EA",
            variant: "-",
            unitPrice: 23.5,
            basePrice: 23.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "GDEW3022WB",
            title: `Galvanized Drip Edge 2"X2" Woodgrain Weathered Bronze`,
            qty: 3,
            uom: "EA",
            variant: "-",
            unitPrice: 23.5,
            basePrice: 23.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
        ],
     },
     { label: "Template 4 (Beacon Template)", value: "template4", 
      items: [
          {
            sku: "410742",
            title: "Owens Corning Oakridge&reg; Shingles",
            qty: 1,
            uom: "BNDL",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["BNDL"],
          },
          {
            sku: "378490",
            title: "Owens Corning Starter Strip Plus Shingle",
            qty: 1,
            uom: "EA",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "651897",
            title: `RhinoRoof 42" x 286' U20 Synthetic Roofing Underlayment - 10 SQ. Roll`,
            qty: 1,
            uom: "RL",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["RL"],
          },
          {
            sku: "262662",
            title: `Owens Corning WeatherLock&reg; Mat Self Sealing Ice & Water Barrier - 2 SQ. Roll`,
            qty: 1,
            uom: "RL",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["RL"],
          },
          {
            sku: "371411",
            title: `Owens Corning 4' VentSure&reg; Heat and Moisture Ridge Vent Strip with Nails`,
            qty: 1,
            uom: "EA",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "577817",
            title: `TRI-BUILT Roof Accessory Spray Paint`,
            qty: 1,
            uom: "EA",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "569818",
            title: `TRI-BUILT Wet/Dry Plastic Roof Cement - Summer Grade`,
            qty: 1,
            uom: "EA",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "603087",
            title: `TRI-BUILT Plastic Cap Nails`,
            qty: 1,
            uom: "EA",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "560196",
            title: `TRI-BUILT Galvanized Adjustable Roof Pipe Flashing`,
            qty: 1,
            uom: "EA",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "448230",
            title: `FlashCo 3" x 3" TPO Clad Metal Drip Edge`,
            qty: 1,
            uom: "EA",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "603800",
            title: `TRI-BUILT Electro-Galvanized Roof Nails`,
            qty: 1,
            uom: "EA",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "576929",
            title: `TRI-BUILT High Performance Polyurethane Sealant`,
            qty: 1,
            uom: "EA",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
          {
            sku: "821871",
            title: `TRI-BUILT Multi-Pitch Galvanized Roof Jack`,
            qty: 1,
            uom: "EA",
            variant: "-",
            basePrice: 12.5,
            unitPrice: 12.5,
            linePrice: 0.0,
            uoms: ["EA"],
          },
        ],
     },
  ];